### CMD line
# fly -t prod sp -p sqlancer -c concourse/pipelines/pipeline.yml -l ~/workspace/gp-continuous-integration/secrets/gpdb_common-ci-secrets.yml -l ~/workspace/gp-continuous-integration/secrets/gpdb_master-ci-secrets.prod.yml
groups:
- name: All
  jobs:
  - sqlancer_gpdb7
  - sqlancer_gpdb6X

#####################################################
#################### RESOURCES ######################
#####################################################

resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
# Image Resources
- name: gpdb7-centos7-test
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb7-centos7-test
    tag: latest

- name: gpdb6-centos7-test
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test
    tag: latest

# Github Source Codes
- name: gpdb7_src
  type: git
  source:
    branch: master
    uri: https://github.com/greenplum-db/gpdb.git
    ignore_paths:
    - gpdb-doc/*
    - README*

- name: gpdb6_src
  type: git
  source:
    branch: 6X_STABLE
    uri: https://github.com/greenplum-db/gpdb.git
    ignore_paths:
    - gpdb-doc/*
    - README*

- name: sqlancer_src
  type: git
  source:
    branch: gp-dev
    uri: https://github.com/gfphoenix78/sqlancer.git

# ccp_src tag_filter is not maintained by gpdb_common-ci-secrets.yml
# so we just pull the laster ccp_src without tag_filter
- name: bin_gpdb7_centos7
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: gpdb_master/bin_gpdb_centos7/bin_gpdb.tar.gz

- name: bin_gpdb6_centos7
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: 6X_STABLE/bin_gpdb_centos7/bin_gpdb.tar.gz

jobs:
- name: sqlancer_gpdb7
  plan:
  - in_parallel:
    - get: gpdb_src
      resource: gpdb7_src
    - get: sqlancer_src
    - get: bin_gpdb
      resource: bin_gpdb7_centos7
    - get: centos-gpdb-dev-7
      resource: gpdb7-centos7-test
  - in_parallel:
    - task: run_sqlancer_gpdb7_planner
      file: sqlancer_src/concourse/tasks/test_sqlancer.yml
      image: centos-gpdb-dev-7
      params:
        TEST_OS: centos
        CONFIGURE_FLAGS: ((configure_flags))
        OPTIMIZER: off
    - task: run_sqlancer_gpdb7_gporca
      file: sqlancer_src/concourse/tasks/test_sqlancer.yml
      image: centos-gpdb-dev-7
      params:
        TEST_OS: centos
        CONFIGURE_FLAGS: ((configure_flags))
        OPTIMIZER: on

- name: sqlancer_gpdb6X
  plan:
  - in_parallel:
    - get: gpdb_src
      resource: gpdb6_src
    - get: sqlancer_src
    - get: bin_gpdb
      resource: bin_gpdb6_centos7
    - get: centos-gpdb-dev-7
      resource: gpdb6-centos7-test
  - in_parallel:
    - task: run_sqlancer_gpdb6_planner
      file: sqlancer_src/concourse/tasks/test_sqlancer.yml
      image: centos-gpdb-dev-7
      params:
        TEST_OS: centos
        CONFIGURE_FLAGS: ((configure_flags))
        OPTIMIZER: off
    - task: run_sqlancer_gpdb6_gporca
      file: sqlancer_src/concourse/tasks/test_sqlancer.yml
      image: centos-gpdb-dev-7
      params:
        TEST_OS: centos
        CONFIGURE_FLAGS: ((configure_flags))
        OPTIMIZER: on

